applications/checklist/urls.py
from django.urls import path
from applications.checklist import views

app_name = 'checklist'
urlpatterns = [
    path('toast', views.toast, name='toast')
]

pgn2023/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.dashboard.urls')),
    path('focal/', include('applications.focal.urls')),
    path('checklist/', include('applications.checklist.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/checklist/models.py
from django.db import models
from applications.account.models import CustomUser, Group


# Create your models here.
class Toast(models.Model):
    SHIFT = (
        ('PAGI', 'PAGI'),
        ('SIANG', 'SIANG'),
        ('MALAM', 'MALAM')
    )

    BOOL_CHOICE = (
        (True, 'Ya'),
        (False, 'Tidak')
    )

    user = models.ForeignKey(CustomUser, related_name='user', on_delete=models.CASCADE)
    group = models.ForeignKey(Group, related_name='group', on_delete=models.CASCADE)
    shift = models.CharField(max_length=10, choices=SHIFT)
    datetime = models.DateField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    siren_one = models.BooleanField(choices=BOOL_CHOICE, default=False)
    siren_two = models.BooleanField(choices=BOOL_CHOICE, default=False)
    siren_three = models.BooleanField(choices=BOOL_CHOICE, default=False)
    siren_four = models.BooleanField(choices=BOOL_CHOICE, default=False)
    seiscomp_one = models.BooleanField(choices=BOOL_CHOICE, default=False)
    seiscomp_two = models.BooleanField(choices=BOOL_CHOICE, default=False)
    seiscomp_three = models.BooleanField(choices=BOOL_CHOICE, default=False)
    toast_one = models.BooleanField(choices=BOOL_CHOICE, default=False)
    toast_two = models.BooleanField(choices=BOOL_CHOICE, default=False)
    disseminate_one = models.BooleanField(choices=BOOL_CHOICE, default=False)
    disseminate_two = models.BooleanField(choices=BOOL_CHOICE, default=False)
    tsp_one = models.BooleanField(choices=BOOL_CHOICE, default=False)
    tsp_two = models.BooleanField(choices=BOOL_CHOICE, default=False)
    wrs = models.BooleanField(choices=BOOL_CHOICE, default=False)
    temperature1 = models.CharField(max_length=10)
    temperature2 = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.datetime}_{self.shift}"

applications/checklist/forms.py
from django import forms
from applications.checklist.models import Toast


class AllForm(forms.ModelForm):
    class Meta:
        model = Toast
        fields = "__all__"
        # fields = [
        #     "user", "group", "shift", "siren_one", "siren_two", "siren_three", "siren_four",
        #     "seiscomp_one", "seiscomp_two", "seiscomp_three", "toast_one", "toast_two",
        #     "disseminate_one", "disseminate_two", "tsp_one", "tsp_two",
        #     "wrs", "temperature1", "temperature2"
        # ]


class UserForm(forms.ModelForm):
    class Meta:
        model = Toast
        fields = ['user', 'group', 'shift', 'datetime']
        widgets = {
            'user': forms.Select(
                attrs={
                    'class': 'form-select'
                }),
            'group': forms.Select(
                attrs={
                    'class': 'form-select'
                }),
            'shift': forms.Select(
                attrs={
                    'class': 'form-select'
                }),
            'datetime': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'type': 'date'
                }
            )
        }

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        # print(self.fields['shift'].empty_string)
        # self.fields['shift'].empty_value = "(Silahkan Pilihft)"
        # print(self.fields['shift'].empty_value)
        self.fields['user'].empty_label = "Silahkan Pilih Nama Operator"
        self.fields['group'].empty_label = "Silahkan Pilih Nama Kelompok"


class SirenForm(forms.ModelForm):
    class Meta:
        model = Toast
        fields = ["siren_one", "siren_two", "siren_three", "siren_four"]
        widgets = {
            "siren_one": forms.RadioSelect(),
            "siren_two": forms.RadioSelect(),
            "siren_three": forms.RadioSelect(),
            "siren_four": forms.RadioSelect()
        }
        help_texts = {
            "siren_one": "Komputer sirine dalam keadaan siap (tidak hang)",
            "siren_two": "Aplikasi sirine dalam keadaan siap (tidak hang)",
            "siren_three": "Checklist salah satu sirine, contoh pemda Padang apakah sirine berubah dari merah menjadi "
                           "kuning? Lakukan untuk pemda dan bmkg  regional lainnya.",
            "siren_four": "Aplikasi Log Note sirine bisa diakses (http://192.168.1.1/bmkg/login/login.php) "
                          "Username: admin, Password: admin"
        }


class SeiscompForm(forms.ModelForm):
    class Meta:
        model = Toast
        fields = ["seiscomp_one", "seiscomp_two", "seiscomp_three"]
        widgets = {
            "seiscomp_one": forms.RadioSelect(),
            "seiscomp_two": forms.RadioSelect(),
            "seiscomp_three": forms.RadioSelect()
        }
        help_texts = {
            "seiscomp_one": "Komputer seiscomp dalam keadaan siap (tidak hang)",
            "seiscomp_two": "Feature seiscomp dapat digunakan (SCOLV, SCRTTV, DLL)",
            "seiscomp_three": "Apakah kondisi sinyal seiscomp masuk"
        }


class ToastForm(forms.ModelForm):
    class Meta:
        model = Toast
        fields = ["toast_one", "toast_two"]
        widgets = {
            "toast_one": forms.RadioSelect(),
            "toast_two": forms.RadioSelect(),
        }
        help_texts = {
            "toast_one": "Komputer TOAST dalam keadaan siap (tidak hang)",
            "toast_two": "Apakah aplikasi TOAST dapat digunakan",
        }


class DisseminateForm(forms.ModelForm):
    class Meta:
        model = Toast
        fields = ["disseminate_one", "disseminate_two"]
        widgets = {
            "disseminate_one": forms.RadioSelect(),
            "disseminate_two": forms.RadioSelect(),
        }
        help_texts = {
            "disseminate_one": "Komputer disseminasi dalam keadaan siap (tidak hang)",
            "disseminate_two": "Aplikasi disseminasi telah ditutup",
        }


class TSPForm(forms.ModelForm):
    class Meta:
        model = Toast
        fields = ["tsp_one", "tsp_two"]
        widgets = {
            "tsp_one": forms.RadioSelect(),
            "tsp_two": forms.RadioSelect(),
        }
        help_texts = {
            "tsp_one": "Komputer TSP dalam keadaan siap (tidak hang)",
            "tsp_two": "Aplikasi TSP telah ditutup",
        }


class WRSForm(forms.ModelForm):
    class Meta:
        model = Toast
        fields = ["wrs"]
        widgets = {
            "wrs": forms.RadioSelect(),
        }
        help_texts = {
            "wrs": "Display Aplikasi WRS NG dalam keadaan aktif",
        }


class TemperatureForm(forms.ModelForm):
    class Meta:
        model = Toast
        fields = ["temperature1", "temperature2"]
        widgets = {
            "temperature1": forms.TextInput(
                attrs={
                    'class': 'form-control text-center',
                    # 'style': "font-size: 12px"
                }
            ),
            "temperature2": forms.TextInput(
                attrs={
                    'class': 'form-control text-center',
                    # 'style': "font-size: 14px"
                }
            ),
        }
        help_texts = {
            "temperature1": "Display Aplikasi WRS NG dalam keadaan aktif",
        }

applications/checklist/views.py
from django.shortcuts import render, redirect
from applications.account.models import CustomUser
from applications.checklist.models import Group
from applications.checklist.forms import SirenForm, AllForm,  \
    SeiscompForm, ToastForm, UserForm, DisseminateForm, TSPForm, WRSForm, TemperatureForm
from applications.checklist.models import Toast


# Create your views here.
def toast(request):
    if request.method == "POST":
        form = AllForm(request.POST)
        # print(form)
        if form.is_valid():
            print("tes")
            form.save()
        else:
            print(form.errors)

            # return redirect()
    else:
        tos = Toast.objects.filter(user__last_name="Saputra")
        print(tos[0].user.full_name())
        # print(all)
    context = {
        'sub': 'Checklist',
        'title': 'Toast',
        'sirens': SirenForm,
        'seiscomps': SeiscompForm,
        'toasts': ToastForm,
        'disseminates': DisseminateForm,
        'tsps': TSPForm,
        'wrss': WRSForm,
        'temperatures': TemperatureForm,
        'users': UserForm()
        # 'users': users,
        # 'groups': groups
    }

    return render(request, 'checklist/toast.html', context)

templates/checklist/toast.html
{% extends 'index.html' %}
{% load static %}

{% block css %}

{% endblock %}

{% block content %}
    <div class="border border-black bg-body p-3">
        <h4 class="text-uppercase text-center">
            <strong>monitoring sirine, toast, aplikasi disseminasi, tsp, wrs</strong>
        </h4>

        <section class="mt-5">
            <form action="" method="post">
            {% csrf_token %}
                <div class="row">
                    <div class="col">
                        <div class="mb-3">
                            <label for="id_user" class="form-label">Operator</label>
                            {{ users.user }}
                        </div>
                        <div class="mb-3">
                            <label for="id_shift" class="form-label">Jadwal Shift</label>
                            {{ users.shift }}
                        </div>
                    </div>

                    <div class="col">
                        <div class="mb-3">
                            <label for="inputOperator" class="form-label">Kelompok</label>
                            {{ users.group }}
                        </div>
                         <div class="mb-3">
                            <label for="inputOperator" class="form-label">Hari / Tanggal</label>
                            {{ users.datetime }}
                        </div>
                    </div>
                </div>


                {% comment %} Monitoring Sirine {% endcomment %}
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr class="text-center">
                        <th scope="col" style="width: 60px">No</th>
                        <th scope="col" style="width: 600px">Monitoring Sirine</th>
                        <th scope="col" colspan="2">Checklist</th>
                    </tr>
                    </thead>
                    <tbody class="text-center">
                    {% for siren in sirens %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td class="text-start">{{ siren.help_text }}</td>
                            {% for field in siren %}
                                <div class="form-check form-check-inline">
                                    <td style="width: 100px">
                                        {{ field.tag }}
                                        <label class="form-check-label"
                                               for="inlineRadio1">{{ field.choice_label }}</label>
                                    </td>
                                </div>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {% comment %} Monitoring Seiscomp {% endcomment %}
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr class="text-center">
                        <th scope="col" style="width: 60px">No</th>
                        <th scope="col" style="width: 600px">Monitoring SeisComP Lt.3</th>
                        <th scope="col" colspan="2">Checklist</th>
                    </tr>
                    </thead>
                    <tbody class="text-center">
                    {% for seiscomp in seiscomps %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td class="text-start">{{ seiscomp.help_text }}</td>
                            {% for field in seiscomp %}
                                <div class="form-check form-check-inline">
                                    <td style="width: 100px">
                                        {{ field.tag }}
                                        <label class="form-check-label"
                                               for="inlineRadio1">{{ field.choice_label }}</label>
                                    </td>
                                </div>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {% comment %} Monitoring TOAST {% endcomment %}
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr class="text-center">
                        <th scope="col" style="width: 60px">No</th>
                        <th scope="col" style="width: 600px">Monitoring TOAST</th>
                        <th scope="col" colspan="2">Checklist</th>
                    </tr>
                    </thead>
                    <tbody class="text-center">
                    {% for toast in toasts %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td class="text-start">{{ toast.help_text }}</td>
                            {% for field in toast %}
                                <div class="form-check form-check-inline">
                                    <td style="width: 100px">
                                        {{ field.tag }}
                                        <label class="form-check-label"
                                               for="inlineRadio1">{{ field.choice_label }}</label>
                                    </td>
                                </div>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {% comment %} Monitoring Disseminasi {% endcomment %}
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr class="text-center">
                        <th scope="col" style="width: 60px">No</th>
                        <th scope="col" style="width: 600px">Monitoring Aplikasi Disseminasi</th>
                        <th scope="col" colspan="2">Checklist</th>
                    </tr>
                    </thead>
                    <tbody class="text-center">
                    {% for disseminate in disseminates %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td class="text-start">{{ disseminate.help_text }}</td>
                            {% for field in disseminate %}
                                <div class="form-check form-check-inline">
                                    <td style="width: 100px">
                                        {{ field.tag }}
                                        <label class="form-check-label"
                                               for="inlineRadio1">{{ field.choice_label }}</label>
                                    </td>
                                </div>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {% comment %} Monitoring Disseminasi {% endcomment %}
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr class="text-center">
                        <th scope="col" style="width: 60px">No</th>
                        <th scope="col" style="width: 600px">Monitoring Aplikasi TSP</th>
                        <th scope="col" colspan="2">Checklist</th>
                    </tr>
                    </thead>
                    <tbody class="text-center">
                    {% for tsp in tsps %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td class="text-start">{{ tsp.help_text }}</td>
                            {% for field in tsp %}
                                <div class="form-check form-check-inline">
                                    <td style="width: 100px">
                                        {{ field.tag }}
                                        <label class="form-check-label"
                                               for="inlineRadio1">{{ field.choice_label }}</label>
                                    </td>
                                </div>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {% comment %} Monitoring WRS NG {% endcomment %}
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr class="text-center">
                        <th scope="col" style="width: 60px">No</th>
                        <th scope="col" style="width: 600px">Monitoring WRS New Gen</th>
                        <th scope="col" colspan="2">Checklist</th>
                    </tr>
                    </thead>
                    <tbody class="text-center">
                    {% for wrs in wrss %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td class="text-start">{{ wrs.help_text }}</td>
                            {% for field in wrs %}
                                <div class="form-check form-check-inline">
                                    <td style="width: 100px">
                                        {{ field.tag }}
                                        <label class="form-check-label"
                                               for="inlineRadio1">{{ field.choice_label }}</label>
                                    </td>
                                </div>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

                {% comment %} Monitoring Temperature {% endcomment %}
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr class="text-center align-middle">
                        <th scope="col" rowspan="2" style="width: 60px">No</th>
                        <th scope="col" rowspan="2" style="width: 600px">Monitoring Suhu</th>
                        <th scope="col" colspan="2">Checklist</th>
                    </tr>
                    <tr class="text-center">
                        <th scope="col" >Rack 1</th>
                        <th scope="col" >Rack 2</th>
                    </tr>
                    </thead>
                    <tbody class="text-center">
                    <tr>
                        <th scope="row" class="align-middle">1</th>
                        <td class="text-start align-middle">
                            Batas suhu untuk Rack I harus < 35, Rack II harus < 30.
                            Jika melebihi batas Max segera hubungi PT.ALC
                        </td>
                        {% for field in temperatures %}
                            <div class="form-check form-check-inline">
                                <td style="width: 100px">
                                    {{ field }}
                                </td>
                            </div>
                        {% endfor %}
                    </tr>
                    {#                    {% for wrs in wrss %}#}
                    {#                        <tr>#}
                    {##}
                    {#                            {% for field in wrs %}#}
                    {#                                <div class="form-check form-check-inline">#}
                    {#                                    <td style="width: 100px">#}
                    {#                                        {{ field.tag }}#}
                    {#                                        <label class="form-check-label"#}
                    {#                                               for="inlineRadio1">{{ field.choice_label }}</label>#}
                    {#                                    </td>#}
                    {#                                </div>#}
                    {#                            {% endfor %}#}
                    {#                        </tr>#}
                    {#                    {% endfor %}#}
                    </tbody>
                </table>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </section>
    </div>
{% endblock %}

{% block script %}

{% endblock %}