applications/checklist/urls.py
from django.urls import path
from applications.checklist import views

app_name = 'checklist'
urlpatterns = [
    path('toast', views.toast, name='toast')
]

applications/dashboard/urls.py
from django.urls import path
from applications.dashboard import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    # path('chart', views.chart, name='chart')
]

applications/focal/urls.py
from django.urls import path
from applications.focal import views

app_name = 'focal'
urlpatterns = [
    path('', views.focal, name='focal'),
    path('getFocal', views.get_focal, name='get_focal'),
]

pgn2023/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.dashboard.urls')),
    path('focal/', include('applications.focal.urls')),
    path('checklist/', include('applications.checklist.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/navbar.html
{% load static %}
<!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">
    <div class="d-flex align-items-center justify-content-between">
        <a href="index.html" class="logo d-flex align-items-center">
            <img src="{% static 'img/gabunglogo.png' %}" alt="">
            <span class="d-none d-lg-block">InaTEWS</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">
            <li class="nav-item dropdown pe-3">
                <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                    <img src="{% static 'img/profile-img.jpg' %}" alt="Profile" class="rounded-circle">
                    <span class="d-none d-md-block dropdown-toggle ps-2">Ade Andika Saputra</span>
                </a><!-- End Profile Image Icon -->

                <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                    <li class="dropdown-header">
                        <h6>Ade Andika Saputra</h6>
                        <span>Admin</span>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                            <i class="bi bi-person"></i>
                            <span>My Profile</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                            <i class="bi bi-gear"></i>
                            <span>Account Settings</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                            <i class="bi bi-question-circle"></i>
                            <span>Need Help?</span>
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>

                    <li>
                        <a class="dropdown-item d-flex align-items-center" href="#">
                            <i class="bi bi-box-arrow-right"></i>
                            <span>Sign Out</span>
                        </a>
                    </li>

                </ul><!-- End Profile Dropdown Items -->
            </li><!-- End Profile Nav -->

        </ul>
    </nav><!-- End Icons Navigation -->

</header><!-- End Header -->

templates/components/sidebar.html
<!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">
    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link " href="{% url 'dashboard:dashboard' %}">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#query-gempabumi-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-menu-button-wide"></i><span>Query Gempabumi</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="query-gempabumi-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{% url 'focal:focal' %}">
                        <i class="bi bi-circle"></i><span>Focal Mechanism</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Query Parameter Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" data-bs-target="#checklist-nav" data-bs-toggle="collapse" href="#">
                <i class="bi bi-menu-button-wide"></i><span>Checklist</span><i class="bi bi-chevron-down ms-auto"></i>
            </a>
            <ul id="checklist-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                <li>
                    <a href="{% url 'checklist:toast' %}">
                        <i class="bi bi-circle"></i><span>Sirine, Toast, Diseminasi, TSP, WRS</span>
                    </a>
                </li>
                <li>
                    <a href="{% url 'checklist:toast' %}">
                        <i class="bi bi-circle"></i><span>PDE dan Peta Harian</span>
                    </a>
                </li>
            </ul>
        </li><!-- End Checklist Nav -->

        <li class="nav-heading">Pages</li>

        <li class="nav-item">
            <a class="nav-link collapsed" href="https://inatews.bmkg.go.id/wrs/index.html">
                <i class="bi bi-person"></i>
                <span>WRS NTWC</span>
            </a>
        </li><!-- End WRS NTWC Link Nav -->

        <li class="nav-item">
            <a class="nav-link collapsed" href="https://inatews.bmkg.go.id/wrs/tsp/index.html">
                <i class="bi bi-question-circle"></i>
                <span>WRS TSP</span>
            </a>
        </li><!-- End WRS TSP Link Nav -->
    </ul>

</aside><!-- End Sidebar-->